/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#f9f9f9',
        'surface-dim': '#dadada',
        'surface-bright': '#f9f9f9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f4f3f3',
        'surface-container': '#eeeeee',
        'surface-container-high': '#e8e8e8',
        'surface-container-highest': '#e2e2e2',
        'surface-variant': '#e2e2e2',
        background: '#f9f9f9',
        primary: '#000000',
        secondary: '#5d5f5f',
        tertiary: '#c76c00',
        'on-primary': '#ffffff',
        'on-secondary': '#ffffff',
        'on-tertiary': '#ffffff',
        'on-surface': '#1a1c1c',
        'on-surface-variant': '#444748',
        'on-background': '#1a1c1c',
        outline: '#747878',
        'outline-variant': '#c4c7c7',
        'surface-tint': '#5f5e5e',
        'inverse-surface': '#2f3131',
        'inverse-on-surface': '#f1f1f1',
        'primary-container': '#1c1b1b',
        'on-primary-container': '#858383',
        'secondary-container': '#dcdddd',
        'on-secondary-container': '#5f6161',
        'tertiary-container': '#2f1500',
        'on-tertiary-container': '#c76c00',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#e5e2e1',
        'primary-fixed-dim': '#c8c6c5',
        'on-primary-fixed': '#1c1b1b',
        'on-primary-fixed-variant': '#474746',
        'secondary-fixed': '#e2e2e2',
        'secondary-fixed-dim': '#c6c6c7',
        'on-secondary-fixed': '#1a1c1c',
        'on-secondary-fixed-variant': '#454747',
        'tertiary-fixed': '#ffdcc3',
        'tertiary-fixed-dim': '#ffb77d',
        'on-tertiary-fixed': '#2f1500',
        'on-tertiary-fixed-variant': '#6e3900',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        sora: ['Sora', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
        geist: ['Geist', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'display-lg': ['Sora', 'sans-serif'],
        'display-lg-mobile': ['Sora', 'sans-serif'],
        'headline-xl': ['Sora', 'sans-serif'],
        'headline-xl-mobile': ['Sora', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-sm': ['Geist', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['64px', { lineHeight: '1.1', letterSpacing: '0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['40px', { lineHeight: '1.2', letterSpacing: '0.02em', fontWeight: '700' }],
        'headline-xl': ['32px', { lineHeight: '1.2', letterSpacing: '0.01em', fontWeight: '600' }],
        'headline-xl-mobile': ['24px', { lineHeight: '1.3', letterSpacing: '0.01em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '1', letterSpacing: '0.08em', fontWeight: '500' }],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        unit: '8px',
        'container-max': '1280px',
        gutter: '24px',
        'margin-desktop': '64px',
        'margin-mobile': '20px',
        'section-gap': '120px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      boxShadow: {
        ambient: '0px 4px 20px rgba(0,0,0,0.04)',
      },
    },
  },
  plugins: [],
}
